// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTxkT_mkYaHYy_19808uO1-HKOQJuJ4Ug',
    appId: '1:36339091491:web:bf16632910a6321bf28996',
    messagingSenderId: '36339091491',
    projectId: 'mealoboxclone',
    authDomain: 'mealoboxclone.firebaseapp.com',
    storageBucket: 'mealoboxclone.appspot.com',
    measurementId: 'G-QTF6Z5S5TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAMrdNX3g28Sy_2FpN5iObN3wmxpcGBCg',
    appId: '1:36339091491:android:d6521a7755de31ccf28996',
    messagingSenderId: '36339091491',
    projectId: 'mealoboxclone',
    storageBucket: 'mealoboxclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2OsgZIP5DRobAfrn96yIUbEfCFnHZiRY',
    appId: '1:36339091491:ios:a95251a255d8ed5af28996',
    messagingSenderId: '36339091491',
    projectId: 'mealoboxclone',
    storageBucket: 'mealoboxclone.appspot.com',
    iosBundleId: 'com.example.mealoboxclone',
  );
}
